module.exports = function(grunt) {


  // now that we've loaded the package.json and the node_modules we set the base path
  // for the actual execution of the tasks
  //grunt.file.setBase('./')

  grunt.loadNpmTasks('grunt-grunticon');
  grunt.loadNpmTasks('grunt-svgmin');
  grunt.loadNpmTasks('grunt-sass');
  grunt.loadNpmTasks('grunt-sass-globbing');
  grunt.loadNpmTasks('grunt-contrib-watch');


  // Project configuration.
  grunt.initConfig({
    
    sass: {
        options: {
            sourceMap: true
        },
        compile: {
            files: [{
                expand: true,
                cwd: 'html/css/sass',
                src: ['*.scss'],
                dest: 'html/css/output',
                ext: '.css'
            }]
        },
        patterns: {
            files: [{
                expand: true,
                cwd: 'html/css/sass/patterns',
                src: ['*.scss'],
                dest: 'html/css/output/patterns',
                ext: '.css'
            }]
        }

    },
    
    /* Sass Globbing preamble:
      
      Sass_globbing creates an 'import map' file (using the first file argument for destination and desired filename) that contains a list of @imports for the files it found at the location in the second argument.
      
      The 'import map' can then be picked up by the regular Sass task, and should be included in global.css or similar master imports file.
      
      The watch task for sass globbing therefore will notice when a new file is added to your globbing location, and update the import map, which will trigger the watch task for sass proper to re-compile. */
    
    sass_globbing: {
      patterns: {
        files: {
          'html/css/sass/_Patterns-ImportMap.scss': 'html/css/sass/patterns/*.scss',
        },
        options: {
          useSingleQuotes: false,
          signature: '// This import map was automatically generated by grunt-sass-globbing. DO NOT EDIT THIS BY HAND - YOUR CHANGES WILL BE OVERWRITTEN.'
        }
      }
    },
    
    grunticon: {
	  icons: {
	    files: [{
              // required config
              expand: true,
              cwd: 'html/assets-icons/src',
              src: ['*.svg', '*.png'],
              dest: "html/assets-icons/output"
             }],

    options: {

      	    // optional config properties

     	      // CSS filenames
      	      datasvgcss: "icons.data.svg.css",
      	      datapngcss: "icons.data.png.css",
      	      urlpngcss: "icons.fallback.css",

      	      // preview HTML filename
      	      previewhtml: "preview.html",

      	      // Unicon loader code snippet filename
              loadersnippet: "unicon.loaderjavascript.txt",

              // folder name (within dest) for png output
              pngfolder: "./png",

              // prefix for CSS classnames
              cssprefix: ".icon-",

              // This allows root-relative referencing of the CSS. If you don't want a prefix path, set to to ""
              cssbasepath: ""
           }
        }
      },
    
    svgmin: {
        options: {
            plugins: [
                {
                    removeViewBox: false
                }, {
                    removeUselessStrokeAndFill: false
                }
            ]
        },
        dist: {
            files: [{
                expand: true,
                cwd: 'html/assets-icons/raw',
                src: ['*.svg'],
                dest: "html/assets-icons/src"
            }]
        }
    },



    watch: {
      sass: {
        files: 'html/css/sass/*.scss',
        tasks: ['sass'],
      },
      sass_globbing: {
        files: 'html/css/sass/patterns/*.scss',
        tasks: ['sass_globbing'],
      },
      svgmin: {
        files: 'html/assets-icons/raw/*.svg',
        tasks: ['svgmin'],
      },
      grunticon: {
        files: 'html/assets-icons/src/*.svg',
        tasks: ['grunticon'],
      },
    },

  });


  // Default task.
  grunt.registerTask('default', ['svgmin', 'grunticon', 'sass', 'sass_globbing' ]);

};
