---
- name: Configure the Nginx PPA
  sudo: yes
  apt_repository: repo=ppa:nginx/{{ nginx_version }} state=present

- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=present

- name: Delete default site
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  register: delete_default_site
  when: nginx_delete_default_site | bool
  notify:
    - Restart Nginx

- name: Delete default web root
  sudo: yes
  file: path=/var/www/html state=absent
  when: nginx_delete_default_site | bool and delete_default_site | changed

- name: Check Nginx Upstart service definition exists
  stat: path=/etc/init/nginx.conf
  register: nginx_upstart

- name: Configure Nginx log rotation
  sudo: yes
  template: src=logrotate_nginx.j2 dest=/etc/logrotate.d/nginx
  when: nginx_upstart.stat.exists

- name: Configure Nginx
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - Restart Nginx
