---
- name: Box Setup - User creation, root lockdown and security patching
  hosts: webservers
  
  vars:
    # What is the repo folder called once cloned?
    repo_name: sfe-style-guide 
    
    # What is the final URL of the project to be? This is used by any non-dev remote server (e.g. production) 
    # provisioned in Nginx conf files.
    server_webserver_name: style.sfe.kin.works
    
    # The URL for the dev remote
    # server_devserver_remote_name:
    
  roles:
    - { role: secure, when: "server_name != 'localhost:8080'" } 
    - { role: lock-out-root-and-pa, when: "server_name != 'localhost:8080'" }
    - { role: remove-box-setup-key, when: "server_name != 'localhost:8080'" }
    - { role: create-kindev-user, when: "server_name != 'localhost:8080'" }
