---
- name: install lemp stack (local) or configure styleguide (remote)
  hosts: webservers
  vars:
    # project_webroot and server_name variables are technically set in 
    # /group_vars/server-type files, but also use some of the variables below.
    
    # What is the repo folder called once cloned?
    - repo_name: sfe-style-guide
    
    # What is the git clone user/address from the project's remote? e.g. git@bitbucket.org:kinworks/foo.git 
    - repo_clone_address: git@github.com:kinworks/sfe-style-guide.git
    
    # What is the final URL of the project to be? This is used by any non-dev remote server (e.g. production) 
    # provisioned in Nginx conf files.
    - server_webserver_name: style.sfe.kin.works
    
    # The URL for the dev remote
    #- server_devserver_remote_name: 
    
    # Server setting variables
    - nginx_delete_default_site: true
    - lemp_upload_max_filesize: 10M
    - lemp_post_max_size: 22M
    
    
  roles:
       # only execute some if not a vagrant box, basically - server_name set in group_vars/
       # note: extra doublequotes round 'when' value due to colon for port confusing parser
     - { role: git-clone, when: "server_name != 'localhost:8080'" }
       # only execute some if we *are* a vagrant box
     - { role: nginx, when: "server_name == 'localhost:8080'" }
     - { role: nginx-config, when: "server_name == 'localhost:8080'" }
     - { role: lemp, when: "server_name == 'localhost:8080'" }
       # only executed if a vagrant box e.g. dev gets devtools
     - { role: kin-devtools, when: "server_name == 'localhost:8080'" }
